# Generated by Django 2.2 on 2020-11-25 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=25, unique=True, verbose_name='Nom de la catégorie')),
                ('desc', models.CharField(max_length=25, verbose_name='Description de la catégorie')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=25, verbose_name='Nom du produit')),
                ('prix', models.IntegerField(verbose_name='Prix du produit')),
                ('image', models.FileField(upload_to='images', verbose_name='Image du produit')),
                ('quantite', models.IntegerField(verbose_name='Quantité du produit')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productmanagement.Categorie', verbose_name='Catégorie')),
            ],
        ),
    ]
